examenParcial/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('gestionTienda/', include('gestionTienda.urls')),
    
]

gestionTienda/urls.py
from django.urls import path
from . import views # . significa directorio local

app_name='gestionTienda'

urlpatterns =[
    path('',views.index,name='index'),
    path('Productos',views.productos,name='productos'),
    path('eliminarProducto/<str:idProducto>',views.eliminarProducto,name='eliminarProducto'),
    path('eliminarTienda/<str:idTienda>',views.eliminarTienda,name='eliminarTienda'),
    path('asignarTienda',views.asignarTienda,name='asignarTienda'),
    path('detalleTienda/<str:idTienda>',views.detalleTienda,name='detalleTienda'),
     
]

gestionTienda/models.py
from django.db import models

# Create your models here.
class Tienda(models.Model):
    direccion=models.CharField(max_length=48, blank=True, null=True)
    provincia=models.CharField(max_length=32, blank=True, null=True)
    region=models.CharField(max_length=16, blank=True, null=True)
    fechaCreacion=models.CharField(max_length=32, blank=True, null=True)
    telefonoContacto=models.CharField(max_length=16, blank=True, null=True)
    

class Producto(models.Model):
    descripcion=models.CharField(max_length=48, blank=True, null=True)
    codigo=models.CharField(max_length=16, blank=True, null=True)
    precioDeVenta=models.CharField(max_length=16, blank=True, null=True)
    cantidad=models.CharField(max_length=16, blank=True, null=True)
    tiendaRelacionada=models.ForeignKey(Tienda, on_delete=models.SET_NULL, blank=True, null=True)
    
    
    
    
    
    
    
    
    
    
    
    
    

gestionTienda/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from .models import Producto, Tienda
from django.urls import reverse

# Create your views here.
def index(request):
    if request.method=='POST':
        nuuevoDireccion=request.POST.get('nuevoDireccion')
        nuevoProvincia=request.POST.get('nuevoProvincia')
        nuevoRegion=request.POST.get('nuevoRegion')
        nuevoFecha=request.POST.get('nuevoFecha')
        nuevoTel=request.POST.get('nuevoTel')
        
        Tienda.objects.create(
            direccion=nuuevoDireccion,
            provincia=nuevoProvincia,
            region=nuevoRegion,
            fechaCreacion=nuevoFecha,
            telefonoContacto=nuevoTel
        )
        
        return HttpResponseRedirect(reverse('gestionTienda:index'))
    return render(request,'tienda.html',{
        'tiendasTotales':Tienda.objects.all()
    })

#{% url 'gestionTienda:Productos' %}
def productos(request):
    if request.method=='POST':
        nuuevoDescripcion=request.POST.get('nuevoDescripcion')
        nuevoPrecio=request.POST.get('nuevoPrecio')
        nuevoCantidad=request.POST.get('nuevoCantidad')
        nuevoProducto=Producto.objects.create(
            descripcion=nuuevoDescripcion,
            precioDeVenta=nuevoPrecio,
            cantidad=nuevoCantidad
        )
        nuevoCodigo=str(nuevoProducto.id)
        while len(nuevoCodigo)<4:
            nuevoCodigo='0'+nuevoCodigo
        nuevoCodigo='PRO-'+nuevoCodigo
        
        nuevoProducto.codigo=nuevoCodigo
        nuevoProducto.save()
        return HttpResponseRedirect(reverse('gestionTienda:productos'))
    return render(request,'productos.html',{
        'productosTotales':Producto.objects.all(),
        'tiendaTotales':Tienda.objects.all()
    })
    
def eliminarProducto(request,idProducto):
    objProducto=Producto.objects.get(id=idProducto)
    objProducto.delete()
    return HttpResponseRedirect(reverse('gestionTienda:productos'))

def eliminarTienda(request,idTienda):
    objTienda=Tienda.objects.get(id=idTienda)
    objTienda.delete()
    return HttpResponseRedirect(reverse('gestionTienda:index'))

def asignarTienda(request):
    if request.method=='POST':
        idProducto=request.POST.get('productoSeleccionado')
        idTienda=request.POST.get('tiendaSeleccionado')
        objProducto=Producto.objects.get(id=idProducto)
        objTienda=Tienda.objects.get(id=idTienda)
        objProducto.tiendaRelacionada=objTienda
        objProducto.save()
        return HttpResponseRedirect(reverse('gestionTienda:productos'))
    
def detalleTienda(request,idTienda):
    objTienda=Tienda.objects.get(id=idTienda)
    datos_Tienda=objTienda.producto_set.all()
    return render(request,'tiendaDetalles.html',{
        'objTienda':objTienda,
        'datos_Tienda':datos_Tienda
    })

gestionTienda/templates/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <!-- Title of the template -->
        <title>Examen Parcial</title>
        <!-- Bootstrap importation -->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
        <!-- FontAwesome importation -->
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css" integrity="sha512-DTOQO9RWCH3ppGqcWaEA1BIZOC6xxalwEsw9c2QQeAIftl+Vegovlnee1c9QX4TctnWMn13TZye+giMm8e2LwA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    </head>
    <body>
        <nav class="navbar navbar-expand-lg bg-dark border-bottom border-body" data-bs-theme="dark">
            <div class="container">
              <a class="navbar-brand" href="{% url 'gestionTienda:index' %}">EXAMEN PARCIAL</a>
              <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
              </button>
              <div class="collapse navbar-collapse nav justify-content-center" id="navbarNav">
                <ul class="navbar-nav w-100 nav-fill">
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'gestionTienda:index' %}">Tiendas</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'gestionTienda:productos' %}">Productos</a>
                  </li>
                </ul>
              </div>
            </div>
          </nav>
            
        <div class="container">
            {% block pageContent %}
            {% endblock %}
        </div>
        
    </body>
</html>

{% block modalContent %}
{% endblock %}

gestionTienda/templates/productos.html
{% extends 'base.html' %}

{% block pageContent %}
            <h1 class="mt-3 mb-3">Productos</h1>
            <a class="btn btn-success text-white mb-3" data-bs-toggle="modal" data-bs-target="#nuevoProducto">Nuevo <i class="fa-brands fa-product-hunt"></i></a>
            <a class="btn btn-success text-white mb-3" data-bs-toggle="modal" data-bs-target="#asignarTienda">Asignar Tienda <i class="fa-solid fa-store"></i></a>
            <div style="overflow-x: auto;">
                <table class="table table-bordered table-hover" id="usersTable" style="font-size: 12px;">
                    <thead class="table-dark">
                        <th scope="col">Descripcion</th>
                        <th scope="col">Codigo</th>
                        <th scope="col">Precio de venta</th>
                        <th scope="col">Cantidad</th>
                        <th scope="col">Tienda distribuidora</th>
                        <th scope="col">Eliminar</th>
                    </thead>
                    <tbody>
                        {% for productoUnitario in productosTotales %}
                        <tr>
                            <td>{{ productoUnitario.descripcion }}</td>
                            <td>{{ productoUnitario.codigo }}</td>
                            <td>{{ productoUnitario.precioDeVenta }}</td>
                            <td>{{ productoUnitario.cantidad }}</td>
                            <td>{{ productoUnitario.tiendaRelacionada.direccion }}</td>
                            <td class="text-center"><a class="btn btn-danger" href="{% url 'gestionTienda:eliminarProducto' productoUnitario.id %}"><i class="fa-solid fa-trash-can"></i></a></td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
{% endblock %}

{% block modalContent %}
<!-- Nuevo Producto modal window -->
<div class="modal fade" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" role="dialog" id="nuevoProducto">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <form action="{% url 'gestionTienda:productos' %}" method="post">
                {% csrf_token %}
                <div class="modal-header">
                    <h5 class="modal-title">Nuevo producto</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <div class="row mb-3 mt-3">
                        <div class="col-12">
                            <label>Descripcion</label>
                            <input type="text" class="form-control" name="nuevoDescripcion" id="nuevoDescripcion" required>
                        </div>
                    </div>
                    <div class="row mb-3">
                        <div class="col-6">
                            <label>Precio de Venta</label>
                            <input type="text" class="form-control" name="nuevoPrecio" id="nuevoPrecio" required>
                        </div>
                        <div class="col-6">
                            <label>Cantidad</label>
                            <input type="text" class="form-control" name="nuevoCantidad" id="nuevoCantidad" required>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancelar</button>
                    <button type="submit" class="btn btn-primary">Agregar</button>
                </div>
            </form>
        </div>
    </div>
</div>

<!-- Asignar Tienda modal window -->
<div class="modal fade" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" role="dialog" id="asignarTienda">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <form action="{% url 'gestionTienda:asignarTienda' %}" method="post">
                {% csrf_token %}
                <div class="modal-header">
                    <h5 class="modal-title">Asignar Tienda</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <div class="row mb-3 mt-3">
                        <div class="col-6">
                            <label>Seleccionar producto</label>
                            <select class="form-select" name="productoSeleccionado" required>
                                <option value=""></option>
                                {% for productoInfo in productosTotales %}
                                <option value="{{ productoInfo.id }}">{{ productoInfo.descripcion }}</option>
                                {% endfor %}
                            </select>
                        </div>
                        <div class="col-6">
                            <label>Seleccionar Tienda</label>
                            <select class="form-select" name="tiendaSeleccionado" required>
                                <option value=""></option>
                                {% for tiendaInfo in tiendaTotales %}
                                <option value="{{ tiendaInfo.id }}">{{ tiendaInfo.direccion }}</option>
                                {% endfor %}
                            </select>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancelar</button>
                    <button type="submit" class="btn btn-primary">Agregar</button>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

gestionTienda/templates/tienda.html
{% extends 'base.html' %}

{% block pageContent %}
            <h1 class="mt-3 mb-3">Tiendas</h1>
            <a class="btn btn-success text-white mb-3" data-bs-toggle="modal" data-bs-target="#nuevoTienda">Nuevo <i class="fa-solid fa-store"></i></a>
            <div style="overflow-x: auto;min-width: auto;">
                <table class="table table-bordered table-hover" id="usersTable" style="font-size: 12px;">
                    <thead class="table-dark">
                        <th scope="col">Direccion</th>
                        <th scope="col">Provincia</th>
                        <th scope="col">Region</th>
                        <th scope="col">Fecha de creacion</th>
                        <th scope="col">Telefono</th>
                        <th scope="col">Productos</th>
                        <th scope="col">Eliminar</th>
                    </thead>
                    <tbody>
                        {% for tiendaUnitario in tiendasTotales %}
                        <tr>
                            <td>{{ tiendaUnitario.direccion }}</td>
                            <td>{{ tiendaUnitario.provincia }}</td>
                            <td>{{ tiendaUnitario.region }}</td>
                            <td>{{ tiendaUnitario.fechaCreacion }}</td>
                            <td>{{ tiendaUnitario.telefonoContacto }}</td>
                            <td class="text-center"><a class="btn btn-warning" href="{% url 'gestionTienda:detalleTienda' tiendaUnitario.id %}"><i class="fa-solid fa-cart-shopping"></i></a></td>
                            <td class="text-center"><a class="btn btn-danger" href="{% url 'gestionTienda:eliminarTienda' tiendaUnitario.id %}"><i class="fa-solid fa-trash-can"></i></a></td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
{% endblock %}

{% block modalContent %}
<!-- New user modal window -->
<div class="modal fade" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" role="dialog" id="nuevoTienda">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <form action="{% url 'gestionTienda:index' %}" method="post">
                {% csrf_token %}
                <div class="modal-header">
                    <h5 class="modal-title">Nueva Tienda</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <div class="row mb-3 mt-3">
                        <div class="col-6">
                            <label>Direccion</label>
                            <input type="text" class="form-control" name="nuevoDireccion" id="nuevoDireccion" required>
                        </div>
                        <div class="col-6">
                            <label>Provincia</label>
                            <input type="text" class="form-control" name="nuevoProvincia" id="nuevoProvincia" required>
                        </div>
                    </div>
                    <div class="row mb-3">
                        <div class="col-6">
                            <label>Region</label>
                            <input type="text" class="form-control" name="nuevoRegion" id="nuevoRegion" required>
                        </div>
                        <div class="col-6">
                            <label>Fecha de creacion</label>
                            <input type="text" class="form-control" name="nuevoFecha" id="nuevoFecha" required>
                        </div>
                    </div>
                    <div class="row mb-3">
                        <div class="col-6">
                            <label>Telefono de contacto</label>
                            <input type="text" class="form-control" name="nuevoTel" id="nuevoTel" required>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancelar</button>
                    <button type="submit" class="btn btn-primary">Agregar</button>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

gestionTienda/templates/tiendaDetalles.html
{% extends 'base.html' %}

{% block pageContent %}
            <h1 class="mt-3 mb-3">Productos asignados a la tienda ubicada en {{ objTienda.direccion }}</h1>
            <a class="btn btn-success text-white mb-3" href="{% url 'gestionTienda:index' %}">Volver a Tiendas <i class="fa-solid fa-store"></i></a>
            <div style="overflow-x: auto;">
                <table class="table table-bordered table-hover" id="usersTable" style="font-size: 12px;">
                    <thead class="table-dark">
                        <th scope="col">Descripcion</th>
                        <th scope="col">Codigo</th>
                        <th scope="col">Precio de venta</th>
                        <th scope="col">Cantidad</th>
                        <th scope="col">Tienda distribuidora</th>
                        <th scope="col">Eliminar</th>
                    </thead>
                    <tbody>
                        {% for productoUnitario in datos_Tienda %}
                        <tr>
                            <td>{{ productoUnitario.descripcion }}</td>
                            <td>{{ productoUnitario.codigo }}</td>
                            <td>{{ productoUnitario.precioDeVenta }}</td>
                            <td>{{ productoUnitario.cantidad }}</td>
                            <td>{{ productoUnitario.tiendaRelacionada.direccion }}</td>
                            <td class="text-center"><a class="btn btn-danger" href="{% url 'gestionTienda:eliminarProducto' productoUnitario.id %}"><i class="fa-solid fa-trash-can"></i></a></td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
{% endblock %}